### PR TITLE
Update sparkle feed url

### PR DESCRIPTION
**Pull request by d33t5**
URL giving 404, updated to the latest feed URL from the VimR.app Info.plist

### CODE REVIEW

**Comment by d33t5** [comment]
Updated Inkscape.pkg to fix pkg error when building

**Comment by homebysix** [comment]
The VimR change looks good to me, but I'd rather hold off on changes to the Inkscape recipe until this issue is resolved: https://github.com/autopkg/homebysix-recipes/issues/130

**Comment by d33t5** [comment]
That issue looks closed unless I am missing something. The parent recipe was updated a few days ago to download version 1.0.0.

**Comment by homebysix** [comment]
Ah, you're right. I needed to `repo-update` the parent. Could you submit a PR with just 6a0a628 included?

**Pull request closed without merging**
