### PR TITLE
Read one extra plist entry to support jamf version strings.

### PR DESCRIPTION
**Pull request by novaksam**

### CODE REVIEW

**Comment by homebysix** [comment]
Does this resolve https://github.com/autopkg/homebysix-recipes/issues/526?

I'm curious where this `jamfversion` environment variable is used downstream.

**Comment by novaksam** [comment]
I use it downstream in a jamfUploader smart group template:

```
<computer_group>
	<name>%GROUP_NAME%</name>
	<is_smart>true</is_smart>
	<criteria>
		<criterion>
			<name>Application Title</name>
			<priority>0</priority>
			<and_or>and</and_or>
			<search_type>is</search_type>
			<value>%APPLICATION_NAME%</value>
		</criterion>
		<criterion>
			<name>Application Version</name>
			<priority>1</priority>
			<and_or>and</and_or>
			<search_type>is not</search_type>
			<value>%jamfversion%</value>
		</criterion>
		<criterion>
			<name>Computer Group</name>
			<priority>2</priority>
			<and_or>and</and_or>
			<search_type>not member of</search_type>
            <value>No check in - 30 days</value>
		</criterion>
	</criteria>
</computer_group>

**Comment by novaksam** [comment]
But yeah, after adjusting smart group templates and such, this would resolve that issue.

**Comment by homebysix** [comment]
Thanks!

**Pull request merged**
