### PR TITLE
New Recipe - Universal R Project Installer

### PR DESCRIPTION
**Pull request by MLBZ521**
Just contributing this `download` recipe to your repo, since it's literally your recipe just combining both the `Intel` and `ARM` architectures into one.  I will use this downstream to create a `.pkg` recipe for a "custom" Universal R Project package.

### CODE REVIEW

**Comment by MLBZ521** [comment]
@homebysix If you'd prefer to not merge this PR, I'll happily add it to my repo.  Just submitted here since it utilizes the same process flow and custom Processor as your architecture specific recipes.

**Comment by homebysix** [comment]
Hi @MLBZ521 - Just confirming, this recipe doesn't actually download a "Universal" version of R, but rather downloads both the x86_64 and arm64 versions separately, right?

What's the benefit of doing this downstream? Is the intent to package them into the same installer that chooses which one to install dynamically?

**Comment by MLBZ521** [comment]
@homebysix Correct.  It isn't downloading a true universal build; my downstream recipe will just create a "universal _package_."  Similar to Rich Trouton's [Universal Adobe CCDA recipes](https://github.com/autopkg/rtrouton-recipes/tree/master/AdobeCreativeCloud).

This is to simply make it easier to manage a single package instead of multiple packages and having to build the scope to properly support both device types.

I have the `.pkg` recipe created, just haven't pushed it to my repo yet.

**Comment by homebysix** [comment]
I think I'd prefer to maintain separate Intel and Apple Silicon recipes rather than combine them together, so I'll let you keep this in your repo.

**Comment by MLBZ521** [comment]
No worries.  I'll just make a note in it that your repo will be needed for the `RProjectURLProvider` Processor.

**Pull request closed without merging**
