### PR TITLE
Added in @macmule's new signing cert

### PR DESCRIPTION
**Pull request by Daz-wallace**

### CODE REVIEW

**Comment by homebysix** [comment]
I'll close this until the re-signing happens.

**Comment by homebysix** [comment]
@macmule Are you still planning to re-sign AutoCasperNBI?

I know there are [no further updates planned](https://macmule.com/2018/10/19/autocaspernbi-autoimagrnbi-1-5-0-the-final-major-updates/), so the AutoPkg recipe is kind of moot, but I want to make sure it's at least current with the latest code signature requirements.

**Comment by macmule** [comment]
@homebysix yes there is a minor release coming.. to fix a desktop issue.. hoping in a matter of weeks too.

So will fix it then

**Comment by macmule** [comment]
Should correct tonight.. had some dev account login fun.. will update here once done & recipe tested.

**Comment by macmule** [comment]
All good!

Apologies for the delay

**Pull request closed without merging**
