### PR TITLE
Hazel 5 is now a .app

### PR DESCRIPTION
**Pull request by macprince**
Hazel 5 has been turned into a .app from a Preference Pane. These changes allow the recipes to download and package Hazel 5.

I'm not entirely certain that this shouldn't be a separate set of recipes (named as `Hazel5`, for instance) but I'm trying to fix/improve existing recipes rather than adding more.

### CODE REVIEW

**Comment by homebysix** [comment]
Thanks for this!

I'm not a Hazel user myself — how smooth is the upgrade from prefpane to app? If both are installed, does the latter clean up the former? Asking to determine whether we need a munki/pkg preinstall script that removes the prefpane prior to installing the app.

**Comment by macprince** [comment]
According to the update notes, it was _supposed to_ remove the prefpane version, but the manual installs I did on two of my machines don't appear to have actually done that. I can work on a Munki `preinstall_script` that will take care of that.

**Comment by macprince** [comment]
I'm not entirely sure how to implement the script into the .pkg recipe. (I don't use the .pkg recipes, just the .munki ones.)

**Comment by homebysix** [comment]
Thanks! I'll take care of the pkg script.

**Pull request merged**
