### PR TITLE
Changes to RingCentral pkg

### PR DESCRIPTION
**Pull request by TSPARR**
Something with my editor has these showing as full rewrite for some reason. At its core, the RingCentral Meetings pkg has changed, so it no longer needs a full repackaging as far as I can tell.

### CODE REVIEW

**Comment by TSPARR** [comment]
This resolves #302 by the way. Forgot to mention that.

**Comment by homebysix** [comment]
The diff is showing a rewrite because of the leading tabs being changed to spaces, most likely. Could you run `plutil -convert xml1 RingCentral/RingCentralMeetings.*.recipe` to fix that?

**Comment by TSPARR** [comment]
Added those requested changes

**Comment by homebysix** [comment]
One of the main reasons to repackage was to avoid the `open "$AppPath"&` command at the end of the vendor postinstall. I believe that used to open an app that would steal focus. Is this still the case?

**Comment by TSPARR** [comment]
Oh I see that now. You are correct. I was focused on the change to script locations rather than the contents of those scripts.

> /Users/munki/Library/AutoPkg/Cache/local.munki.RingCentralMeetings/expanded/Scripts/zm.zip with ditto failed: ditto: /Users/munki/Library/AutoPkg/Cache/local.munki.RingCentralMeetings/expanded/Scripts/zm.zip: No such file or directory


```
################################################
#start new app
################################################

open "$AppPath"&
echo "["$(date)"] start new app: $AppPath">>"$LOG_PATH"

exit 0
```

So we will still need to repackage to remove that piece.

**Comment by TSPARR** [comment]
@homebysix I believe this is correct now. Reverted .munki recipe now that we're back to repackaging, edited .pkg to account for changes, and edited postinstall to incorporate upstream fixes from looks like Zoom's postinstall.

**Comment by TSPARR** [comment]
Hey @homebysix just wanted to see if you had any other qualms about merging this. We ran the latest version and have rolled out the created pkg to customers and everything seems to be working as far as I can tell.

**Comment by sphen13** [comment]
This seems to work for me

**Comment by ChefAustin** [comment]
This also works for me. Hoping the changes are agreeable with @homebysix so this can be landed. 🤞

**Comment by sphen13** [comment]
any thoughts on merging this @homebysix ?

**Comment by homebysix** [comment]
Works for me. Thank you!

**Pull request merged**
