### PR TITLE
Update Spotify.pkg.recipe AND Slight PyLint changes

### PR DESCRIPTION
**Pull request by jgstew**
proposed change to address https://github.com/autopkg/homebysix-recipes/issues/340

I tested this before, after, and with changed `VERSION_SPLIT_ON` value to see that it satisfies the request.

Also tested overriding it using:

```
autopkg run -v --key VERSION_SPLIT_ON=FakeStringDoNotSplit Spotify.pkg.recipe
```

With the desired output with this override as being:

```
VersionSplitter: Split version: 1.1.54.592.gc0b20638
```

But without this override:

```
VersionSplitter: Split version: 1.1.54.592
```

### CODE REVIEW

**Comment by jgstew** [comment]
I also tweaked the pylint stuff slightly.

**Comment by jgstew** [comment]
added a flake8 github action as well, while I'm at it.

also, FYI, the github actions respect the .pylintrc and .flake8 config files already in the repo which is neat.

**Comment by jgstew** [comment]
oh, shoot, my copy - paste of the spotify recipie changes was bad.

**Comment by jgstew** [comment]
I thought the diff looked odd when I first made this but I thought it was just a mistake in the way the diff was seeing the changes, but no, it was my bad.

**Comment by homebysix** [comment]
Thanks for this! Very creative to use an input variable for conditional splitting. 👍

**Pull request merged**
