### PR TITLE
Update the package creation to work from the IT distribution package (now downloaded by Hansen's recipe)

### PR DESCRIPTION
**Pull request by ygini**
Updating Zoom package creation to use the enterprise distribution package

Even if it's an enterprise distribution one, we still have to fix it, the postinstall script is a poorly written mess…

### CODE REVIEW

**Comment by arubdesu** [comment]
I'm not sure I want the scripts at all, since I don't rely on a previous version with kexts so I don't want/need any of that handling, so I may fork this and call it the 'IT deploy' version

**Comment by homebysix** [comment]
Some casual testing seems to indicate that this PR works, so I'm going to merge it. If one of you would like to run more in-depth testing, that would be very appreciated. Thanks!

**Comment by mpanighetti** [comment]
Works great in my testing, thanks for merging!

**Comment by kitzy** [comment]
Works fine here!

**Pull request merged**
