### PR TITLE
Code sig ver for Grand Perspective

### PR DESCRIPTION
**Pull request by aysiu**
Added code signature verification for Grand Perspective download recipe.

### CODE REVIEW

**Comment by homebysix** [comment]
You may want to make the same suggestion for this recipe:
https://github.com/autopkg/jessepeterson-recipes/blob/master/GrandPerspective/GrandPerspective.munki.recipe

**Comment by aysiu** [comment]
There are two recipes for download?

**Comment by homebysix** [comment]
Jesse's munki recipe was written before `ParentRecipe` was a thing, I suspect, so it does the download and Munki import all in one shot. There are a few old recipes like that around.

The reason I maintain a separate download recipe is for the benefit of people who want to download, pkg, or import the app but don't use Munki.

**Comment by aysiu** [comment]
I wonder if it'd make sense, then, for the pull request to use this download as a parent recipe instead of putting the code signature verification in there?

**Comment by homebysix** [comment]
Yes, that would be a fine solution too.

**Comment by aysiu** [comment]
Cool. I'll wait to hear from jessepeterson.

**Comment by jessepeterson** [comment]
`ParentRecipe` was a new-ish thing back then, but it did exist. However because I only use Munki I have limited use of separate download recipes and nobody submitted a PR to add separate ones. :)

The only difference between them that I see is that much of the Processor details have been split out into top-level `Input` variables. Also, `SourceForgeURLProvider` now handles SF project _names_, which my recipe is using whereas the old-style project ID is being used here.

But: yes, I'd be open to any PRs.

**Comment by aysiu** [comment]
Thanks, @jessepeterson. I'll see if I can throw something together, and then it's up to you if you want to put that change through.

**Comment by aysiu** [comment]
Hm. Actually, I'm wondering if we should leave it be. I just noticed there are two Munki recipes!

Here's the homebysix one:
https://github.com/autopkg/homebysix-recipes/blob/master/GrandPerspective/GrandPerspective.munki.recipe

Here's the jessepeterson one:
https://github.com/autopkg/jessepeterson-recipes/blob/master/GrandPerspective/GrandPerspective.munki.recipe

The homebysix one is basically what I was going to create, but that already exists...

**Comment by jessepeterson** [comment]
`SourceForgeURLProvider` lives with my GrandPerspective directory that I think a bunch of folks use in their recipes so unfortunately I can't just remove it.

How about I just change my recipe to have @homebysix's as the parent and just make my recipe sorta empty? A recipe "symlink" of sorts. :)

**Comment by homebysix** [comment]
@jessepeterson The problem with that is it'll break the recipe for people who haven't already added my repo. Easy to fix, but still annoying for some I'm sure.

I think we may want to fix one thing at a time. For now, that thing is adding code signature verification, which should probably be added to both @jessepeterson's GrandPerspective.munki recipe and my GrandPerspective.download recipe.

Later, we can tackle the problem of recipe duplication. I think a solution to that will be easier in a few months than it is now, given some of the ideas proposed on autopkg-discuss recently.

**Comment by jessepeterson** [comment]
Yeah that sounds like a plan. One other difference in the recipes is that I have the overridable customization of where to install the app. In our environment that app goes into /Apps/Utilities.

**Pull request merged**
