### PR TITLE
R: URL Update

### LINKED ISSUE #427: r.munki stops working -> Mismatch in authority names
r.munki works till version 4.0.5

Version 4.1.0 is released (18-05-2021) and stops working.

R.munki...
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
 
The following recipes failed:
    R.munki
        Error in local.munki.R: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
 
Nothing downloaded, packaged or imported.

**Next I did this:** 

autopkg run -k DISABLE_CODE_SIGNATURE_VERIFICATION=1  R.munki
Processing R.munki...
 
The following new items were imported into Munki:
    Name  Version  Catalogs  Pkginfo Path          Pkg Repo Path       Icon Repo Path  
    ----  -------  --------  ------------          -------------       --------------  
    R     3.3.3    pretest   apps/R/R-3.3.3.plist  apps/R/R-3.3.3.pkg    

**It downloads an old version**

**If i run it again:**

autopkg run R.munki
Processing R.munki...
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
 
The following recipes failed:
    R.munki
        Error in local.munki.R: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
 
Nothing downloaded, packaged or imported.

### PR DESCRIPTION
**Pull request by primalcurve**
Tweak to regex to find latest version link.

Fixes #427

### CODE REVIEW

**Comment by primalcurve** [comment]
Okay this requires further tweaking because `URLDownloader` is trying to move the file to `CACHE_DIR/downloads/base/R-<version>.pkg`. Fun!

**Comment by primalcurve** [comment]
Here we go. Got there eventually lol.

```shell
% autopkg run -vvvv ~/<repo-parent>/homebysix-recipes/R/R.download.recipe
Processing /Users/<redacted>/<repo-parent>/homebysix-recipes/R/R.download.recipe...
WARNING: /Users/<redacted>/<repo-parent>/homebysix-recipes/R/R.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3',
 'NAME': 'R',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R',
 'RECIPE_DIR': '/Users/<redacted>/<repo-parent>/homebysix-recipes/R',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/<redacted>/<repo-parent>/homebysix-recipes/R/R.download.recipe',
 'RECIPE_REPOS': {'/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {'URL': 'https://github.com/autopkg/n8felton-recipes'},
                  '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes'],
 'verbose': 4}
URLTextSearcher
{'Input': {'re_pattern': '<a '
                         'href="base/(?P<filename>R-(?P<version>[\\d.]+)\\.pkg)">R-[\\d.]+\\.pkg</a>',
           'url': 'https://cran.r-project.org/bin/macosx/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://cran.r-project.org/bin/macosx/']
URLTextSearcher: Found matching text (filename): R-4.1.0.pkg
URLTextSearcher: Found matching text (version): 4.1.0
URLTextSearcher: Found matching text (match): R-4.1.0.pkg
{'Output': {'filename': 'R-4.1.0.pkg',
            'match': 'R-4.1.0.pkg',
            'version': '4.1.0'}}
URLDownloader
{'Input': {'filename': 'R-4.1.0.pkg',
           'url': 'https://cran.r-project.org/bin/macosx/base/R-4.1.0.pkg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Curl command: ['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://cran.r-project.org/bin/macosx/base/R-4.1.0.pkg', '--fail', '--output', '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/tmpqr0ch_mr']
URLDownloader: Storing new Last-Modified header: Thu, 20 May 2021 05:38:50 GMT
URLDownloader: Storing new ETag header: "563f326-5c2bc5b9f48a9"
URLDownloader: Downloaded /Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg
{'Output': {'download_changed': True,
            'etag': '"563f326-5c2bc5b9f48a9"',
            'last_modified': 'Thu, 20 May 2021 05:38:50 GMT',
            'pathname': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'expected_authority_names': ['Developer ID Installer: Simon Urbanek '
                                        '(VZLD955F6P)',
                                        'Developer ID Certification Authority',
                                        'Apple Root CA'],
           'input_path': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg'}}
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "R-4.1.0.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-05-20 02:40:29 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Simon Urbanek (VZLD955F6P)
CodeSignatureVerifier:        Expires: 2022-05-30 12:52:25 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            DC 71 49 90 95 59 7F 5B 7E 61 7F 26 24 44 AE 8B A7 96 AA 11 C2 8B
CodeSignatureVerifier:            0E 6D EB B9 37 2A 80 78 AF A0
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier:
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
{'AUTOPKG_VERSION': '2.3',
 'CHECK_FILESIZE_ONLY': False,
 'NAME': 'R',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R',
 'RECIPE_DIR': '/Users/<redacted>/<repo-parent>/homebysix-recipes/R',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/<redacted>/<repo-parent>/homebysix-recipes/R/R.download.recipe',
 'RECIPE_REPOS': {'/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {'URL': 'https://github.com/autopkg/n8felton-recipes'},
                  '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/<redacted>/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes'],
 'download_changed': True,
 'etag': '"563f326-5c2bc5b9f48a9"',
 'expected_authority_names': ['Developer ID Installer: Simon Urbanek '
                              '(VZLD955F6P)',
                              'Developer ID Certification Authority',
                              'Apple Root CA'],
 'filename': 'R-4.1.0.pkg',
 'input_path': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg',
 'last_modified': 'Thu, 20 May 2021 05:38:50 GMT',
 'match': 'R-4.1.0.pkg',
 'pathname': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg',
 'prefetch_filename': False,
 're_pattern': '<a '
               'href="base/(?P<filename>R-(?P<version>[\\d.]+)\\.pkg)">R-[\\d.]+\\.pkg</a>',
 'result_output_var_name': 'match',
 'url': 'https://cran.r-project.org/bin/macosx/base/R-4.1.0.pkg',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 4,
 'version': '4.1.0'}
Receipt written to /Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/receipts/R.download-receipt-20210521-094517.plist

The following new items were downloaded:
    Download Path
    -------------
    /Users/<redacted>/Library/AutoPkg/Cache/com.github.homebysix.download.R/downloads/R-4.1.0.pkg
```

**Comment by primalcurve** [comment]
I am also playing around with optional input keys for the recipe that would allow an override to be created to download the ARM64 version, but I will wait for this PR to complete before I introduce that.

**Comment by homebysix** [comment]
Thanks! Didn't see this PR until after I added #430 to address #427.

**Pull request closed without merging**
