### PR TITLE
Update GitHubCLI.munki.recipe

### PR DESCRIPTION
**Pull request by kevinmcox**
Adds the Munki `supported_architectures` array.

### CODE REVIEW

**Comment by homebysix** [comment]
Correct me if I'm wrong, but doesn't this require AutoPkg users to specify both `SUPPORTED_ARCH` and [`ARCH`](https://github.com/autopkg/homebysix-recipes/blob/master/GitHub/GitHubCLI.download.recipe#L15-L16) variables, whereas before the change they only had to specify the `ARCH` variable along with adding a `supported_architectures` array into their override?

Given the need to keep these two variables in sync, I'm not sure this change makes things easier or clearer.

**Comment by kevinmcox** [comment]
Correct, and this is how it is handled in several other recipes currently:
https://github.com/autopkg/gregneagle-recipes/blob/master/Podman/Podman.munki.recipe#L7-L8
https://github.com/autopkg/timsutton-recipes/blob/master/Go/Go.munki.recipe#L18-L22

The main difference is that currently this recipe assumes that users already know that they need to add a `supported_architectures` array into their override.

The change proposed here makes it explicit that one should be used and guides users on how to do it.

But I agree this isn't optimal so I submitted a PR to Munki in hopes of allowing a single variable to work for both the download URL and Munki array: https://github.com/munki/munki/pull/1221

**Comment by kevinmcox** [comment]
@homebysix I pushed a new commit, let me know if you like this approach better.

**Comment by homebysix** [comment]
I like the new approach! Less work for recipe users and authors alike. Thank you! 👍

**Comment by kevinmcox** [comment]
Now if we could get `FindAndReplace` added as a core processor it would make this approach more universally accessable without adding a dependency of this repo... 😉

**Pull request merged**
